### ISSUE TITLE
Multi-architecture OpenShift Origin demo for KubeCon Austin 2017

### ISSUE THREAD

**Issue by detiber** [WorksOnArm/cluster#29] opened 2017-12-01 16:03 UTC
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Jason DeTiberus, jdetiber@redhat.com, Red Hat, Inc, Principal Software Engineer
Josh Berkus, jberkus@redhat.com, Red Hat, Inc, Principal Program Manager

### Project Title and description

OpenShift Origin is a distribution of Kubernetes optimized for continuous application development and multi-tenant deployment. OpenShift adds developer and operations-centric tools on top of Kubernetes to enable rapid application development, easy deployment and scaling, and long-term lifecycle maintenance for small and large teams.

### Which members of the community would benefit from your work?

People that are interested in building and running multi-architecture OpenShift Origin Clusters

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, https://github.com/openshift/origin

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

2 Type 2A hosts with a single public IP each

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

These hosts would only be needed through the end of KubeCon (Dec 8, 2017)

### Please state your contributions to the open source community and any other relevant initiatives

The OpenShift team at Red Hat is comprised of core contributors to a number of Open Source communities including Kubernetes and Docker. This demo is part of our initiatives to bring OpenShift to architectures other than x86_64.

**Comment by vielmetti** [comment] 2017-12-01 16:42
@detiber - if you can put a second person on your project team we'd appreciate it - it's always good to have more than one contact for efforts, just to be sure that there's more than one person we can go to if there's any urgent questions.

**Comment by detiber** [comment] 2017-12-01 16:45
@vielmetti I added Josh Berkus as a backup contact.

**Comment by vielmetti** [comment] 2017-12-01 18:14
Approved! Please create a Packet account and then email me the UUID for the project, I'll set it up for you.

**Comment by zlim** [comment] 2017-12-04 20:27
Very interesting! Is it possible to share blogs/videos/etc. related to this request?

Also, is it possible to share the recipe so others can reproduce this work/demo on-demand?

**Comment by detiber** [comment] 2017-12-05 07:44
@zlim yes, I will be following up with a blog and publishing docs and scripts to reproduce the demo following the completion of KubeCon.

**Comment by vielmetti** [comment] 2018-06-20 19:21
Hey @detiber - hoping to wrap up this open issue, if you have any artifacts or notes from the demo that have already been done I'm happy to share.

I know that time has marched on since my last query so if this should be closed for some other reason that's fine.

**Comment by detiber** [comment] 2018-06-26 03:36
@vielmetti time got away from me with the employer/focus change and I never got a chance to wrap things up cleanly enough to produce any useable content.

**Comment by vielmetti** [comment] 2018-06-26 03:38
Fair enough @detiber ! I’ll close this out with that note and thank you for your efforts.

**Closed by vielmetti** 2018-06-26 03:38 UTC
Labels: approved, completed, demo/kubecon-austin-2017, needs/blog-post
